### ISSUE TITLE
squeeze out more performance in case of no pointer aliasing

### ISSUE THREAD

**Issue by timotheecour** [libmir/mir-blas#2]
@9il 

fortran can often be faster than C/C++ by assuming possibility of aliasing of memory pointers, allowing for better code generation, see for eg:
https://stackoverflow.com/questions/146159/is-fortran-easier-to-optimize-than-c-for-heavy-calculations/146186#146186

This has been proposed in D in https://issues.dlang.org/show_bug.cgi?id=10750 but not sure anything happened on this.

* maybe a lot of mir functionality could get a nice speed upgrade by implementing this feature. Is there any way to have a small experiment show what kind of speedup one could get (eg in a matrix vector operation)?

* That raises a question of how to let caller inform a function that the input pointers/slices have no aliasing. 
A runtime check would probably be possible and add negligible runtime cost?

## relevant links
https://github.com/dlang/druntime/pull/1891 templated array ops #1891
http://en.cppreference.com/w/c/language/restrict restrict type qualifier
https://forum.dlang.org/post/sqfyzbgscacupthtwugj@forum.dlang.org C `restrict` keyword in D
> In C, the `restrict` keyword implies that 2 or more pointer arguments in a function call do not point to the same data. This allows for some additional optimizations which were not possible before, finally making C as fast as Fortran.

**Comment by 9il** [comment]
`mir-blas` is only wrapper around BLAS API
No plan for now to write own BLAS implementation
